server:
  port: 6001

spring:
#配置数据库连接
  datasource:
    url: jdbc:mysql://rm-bp11j3dwvjw3942g17o.mysql.rds.aliyuncs.com:3306/cloud_blog?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: marker_db
    password: shuqi19990107
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 172.26.145.223
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  mail:
    host: smtp.163.com
    username: muaker@163.com
    password: KBYCVXXLRZGMZNJS
    port: 25
    protocol: smtp
    default-encoding: utf-8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis-plus:
  mapper-locations: classpath:com/mark/*/mapper/xml/*.xml

aliyun:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4GHRz68KqbqfrrFeWufk
  accessKeySecret: sl8OlNPFuY9kGljvavTp7IcqCuGNfS
  oss:
    bucketName: marker-fileupload
    filePatten: images/muke/blog/prod

blog:
  article:
    hotConditionVal: 100

site:
  subject: 木可个人博客网站
  siteUrl: http://www.lishuqi.top

third:
  login:
    github:
      clientId: 6448bac1b7b91ae9a4b6
      secret: 301d8e69187c1e654e4ddcc5f106a9679da54d59
      redirectUrl: http://8.131.86.202:6001/api/ucenter/login/github/callback
    gitee:
      clientId: 95e5955cc4f249ec6c421609d6501ef14b1b27b9c958c41449547a1d690d074b
      secret: e4840073f19b91022172b39de5ebda4f0f9b4bce17ecba15a885dc84c5c693e4
      redirectUrl: http://8.131.86.202:6001/api/ucenter/login/gitee/callback
